prepend-rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,anyrouter.top,PROXY
  - RULE-SET,community-direct,DIRECT
  - RULE-SET,service-direct,DIRECT
  - RULE-SET,mirror-direct,DIRECT
  - RULE-SET,transfer-proxy,PROXY
  - RULE-SET,service-proxy,PROXY
  - RULE-SET,mirror-proxy,PROXY
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - RULE-SET,google,PROXY
  - RULE-SET,applications,DIRECT
  - RULE-SET,manga,DIRECT
  - RULE-SET,video,DIRECT
  - RULE-SET,steam-cn,DIRECT
  - RULE-SET,steam,DIRECT # YOU KNOW WHEN TO UN-COMMENT THIS
  # - RULE-SET,steam,PROXY
  # - RULE-SET,spotify,PROXY
  - RULE-SET,cdn,PROXY
  - RULE-SET,applications-direct,DIRECT
  - RULE-SET,applications-proxy,PROXY
  - RULE-SET,applications-reject,REJECT
  - RULE-SET,adobe,REJECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
